#!/bin/bash

LOCAL_INSTALL="/home/$USER"

help()
{
    echo "usage"
    echo "$0 push          update configs and sync repo to local repository"
    echo "$0 pull          install configs (highly discouraged)"
}

if [ $# == 1 ]; then
  if [ $1 == push ]; then
    # save i3 config
    cp -pr ~/.config/i3/config i3.conf
    cp -pr ~/.i3status.conf i3status.conf
    cp -pr ~/.config/picom.conf .
    # clone icons and theme
    cp -pr ~/.icons/* icons
    cp -pr ~/.themes/* themes
    cp -pr ~/.config/gtk-3.0 gtk/
    cp -pr ~/.gtkrc-2.0 gtk/gtkrc-2.0
    # save polybar
    cp -pr ~/.config/polybar .
    cp -pr ~/.config/cava .
    cp -pr ~/.ncmpcpp ncmpcpp
    cp -pr ~/.config/rofi .
    cp -pr ~/.config/termite .
  elif [ $1 == pull ]; then
    mkdir -p $LOCAL_INSTALL/.{i3,icons,themes,.config/gtk-3.0,.gtkrc-2.0}
    # restore i3 config
    cp -pr i3.conf $LOCAL_INSTALL/.config/i3/config
    cp -pr i3status.conf $LOCAL_INSTALL/.i3status.conf
    cp -pr picom.conf $LOCAL_INSTALL/.config/
    # copy the gtk theme
    cp -pr gtk/gtk-3.0 $LOCAL_INSTALL/.config/gtk-3.0
    cp -pr gtk/gtkrc-2.0 $LOCAL_INSTALL/.gtkrc-2.0
    cp -pr icons/* $LOCAL_INSTALL/.icons/
    cp -pr themes/* $LOCAL_INSTALL/.themes/
    # copy polybar
    cp -pr polybar $LOCAL_INSTALL/.config/
    cp -pr ncmpcpp $LOCAL_INSTALL/.ncmpcpp
    cp -pr cava $LOCAL_INSTALL/.config/
    # save rofi theme
    cp -pr rofi $LOCAL_INSTALL/.config/
    cp -pr termite $LOCAL_INSTALL/.config/
    # cp -pr wine/user.reg $LOCAL_INSTALL/.wine
  else
    echo "Wrong parametres"
    help
    exit 1
  fi
else
  help
fi

